/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Controllers.comprobanteManager;
import Controllers.operadoresManager;
import Controllers.porcentajeComiManager;
import conexion.GenericRepository;
import datos.dComisiones;
import datos.dCuentasCorriente;
import datos.dDetalleVta;
import datos.dIva;
import datos.dOperadores;
import datos.dProductos;
import datos.dStock;
import datos.dTipoComprobante;
import datos.dVendedor;
import datos.dVentas;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static vistas.vPrincipal.factory;
/**
 *
 * @author BeltariT
 */
public class vVentas extends javax.swing.JInternalFrame {
    
//    SessionFactoryManager manager = new SessionFactoryManager();
//        SessionFactory factory = manager.getSessionFactory();

//    GenericRepository<dVentas, Long> func = new GenericRepository<dVentas, Long>() {
//    };
//
//    GenericRepository<dOperadores, Long> funcOP = new GenericRepository<dOperadores, Long>() {
//    };
//    GenericRepository<dVendedor, Long> funcVENDED = new GenericRepository<dVendedor, Long>() {
//    };
//    GenericRepository<dProductos, Long> funcPRO = new GenericRepository<dProductos, Long>() {
//    };
//    GenericRepository<dCuentasCorriente, Long> funcCC = new GenericRepository<dCuentasCorriente, Long>() {
//    };
//    GenericRepository<dTipoComprobante, Long> funcCO = new GenericRepository<dTipoComprobante, Long>() {
//    };
//     GenericRepository<dDetalleVta, Long> funcVTA = new GenericRepository<dDetalleVta, Long>() {
//        };
//
//        GenericRepository<dStock, Long> funcSTO = new GenericRepository<dStock, Long>() {
//        };
//        GenericRepository<dComisiones, Long> funcCOMI = new GenericRepository<dComisiones, Long>() {
//        };

    dVentas dts = new dVentas();
//    dDetalleVta dtsVent = new dDetalleVta();
//    dOperadores dtsOpera = new dOperadores();
//    dTipoComprobante dtsComprobante = new dTipoComprobante();
//    dComisiones dtsComi = new dComisiones();
//    dVendedor dtsVendedor = new dVendedor();
    java.util.Date dato = null;

    public vVentas() {
        initComponents();
        inHabilitar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void habilitar() {

        txtId.setText("");
        txtRazon.setText("");
        txtDireccion.setText("");
        txtLocalidad.setText("");
        txtIdVendedor.setText("");
        txtVendedor.setText("");
        txtIdComprobante.setText("");
        txtTipoComprobante.setText("");
        txtNumero.setText("");
        txtObservacion.setText("");
        txtFecha.setText("");
        txtTotal.setText("");

        txtId.setEnabled(true);
        txtRazon.setEnabled(true);
        txtDireccion.setEnabled(true);
        txtLocalidad.setEnabled(true);
        txtIdVendedor.setEnabled(true);
        txtVendedor.setEnabled(true);
        txtIdComprobante.setEnabled(true);
        txtTipoComprobante.setEnabled(true);
        txtNumero.setEnabled(true);
        txtObservacion.setEnabled(true);
        txtFecha.setEnabled(true);

        txtIdProducto.setEnabled(true);
        txtProducto.setEnabled(true);
        txtPrecio.setEnabled(true);
        txtCantidad.setEnabled(true);

        btnGuardar.setEnabled(true);
        fechaActual();

    }

    public void inHabilitar() {

        txtId.setEnabled(false);
        txtRazon.setEnabled(false);
        txtDireccion.setEnabled(false);
        txtLocalidad.setEnabled(false);
        txtIdVendedor.setEnabled(false);
        txtVendedor.setEnabled(false);
        txtIdComprobante.setEnabled(false);
        txtTipoComprobante.setEnabled(false);
        txtNumero.setEnabled(false);
        txtObservacion.setEnabled(false);
        txtFecha.setEnabled(false);

        txtIdProducto.setEnabled(false);
        txtProducto.setEnabled(false);
        txtPrecio.setEnabled(false);
        txtCantidad.setEnabled(false);

        btnGuardar.setEnabled(false);

    }

    public void limpiaTabla() { /// METODO LIMPIAR TABLA (NO FUNCIONA)
        try {
            DefaultTableModel temp = (DefaultTableModel) tableVenta.getModel();
            int a = temp.getRowCount();
            for (int i = 0; i < a; i++) {
                temp.removeRow(0); //aquí estaba el error, antes pasaba la i como parametro.... soy un bacín  XD
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void agregarProducto() {

        double sum = Double.parseDouble(txtPrecio.getText()) * Double.parseDouble(txtCantidad.getText());

        txtSubTotal.setText(String.valueOf(sum));

        Object[] datos = new Object[]{txtIdProducto.getText(), txtProducto.getText(), txtCantidad.getText(), txtPrecio.getText(), txtSubTotal.getText()};

        DefaultTableModel model = (DefaultTableModel) tableVenta.getModel();
        model.addRow(datos);
        tableVenta.setModel(model);

        txtIdProducto.setText("");
        txtProducto.setText("");
        txtCantidad.setText("");
        txtPrecio.setText("");
        txtSubTotal.setText("");

        suma();

    }

    public void suma() {

        double valor = 0;

        int filas = tableVenta.getRowCount();

        for (int i = 0; i < filas; i++) {

            String tol = String.valueOf(tableVenta.getValueAt(i, 4));

            double total = Double.parseDouble(tol);

            valor = valor + total;

        }
        txtSubtotal.setText(String.valueOf(valor));
        txtTotal.setText(String.valueOf(valor));

    }

    public void guardar() {
        
        if (txtId.getText().length()==0) {
            JOptionPane.showMessageDialog(null,"FALTA RAZON SOCIAL","ADVERTENCIA",JOptionPane.ERROR_MESSAGE);
            txtId.requestFocus();
            return ;
        }

        if (txtFecha.getText().length()==0) {
            JOptionPane.showMessageDialog(null,"FALTA FECHA","ADVERTENCIA",JOptionPane.ERROR_MESSAGE);
            txtFecha.requestFocus();
            return ;
        }
        if (txtIdComprobante.getText().length()==0) {
            JOptionPane.showMessageDialog(null,"FALTA COMPROBANTE","ADVERTENCIA",JOptionPane.ERROR_MESSAGE);
            txtIdComprobante.requestFocus();
            return ;
        }
        GenericRepository<dVentas, Long> func = new GenericRepository<dVentas, Long>(factory) {
        };
        
        GenericRepository<dOperadores, Long> funcOP = new GenericRepository<dOperadores, Long>(factory) {
        };  
        GenericRepository<dTipoComprobante, Long> funcCO = new GenericRepository<dTipoComprobante, Long>(factory) {
        };

        obtenerFecha();

       dOperadores dtsOpera = funcOP.getById(Long.valueOf(txtId.getText()));
       dTipoComprobante dtsComprobante = funcCO.getById(Long.valueOf(txtIdComprobante.getText()));

        dts.setOperadores(dtsOpera);
        if(txtNumero.getText().length()==0){
         dts.setComprobante(0);}
        else{
        dts.setComprobante(Integer.parseInt(txtNumero.getText()));}
        dts.setDescripcion(txtTipoComprobante.getText()+ " "+txtObservacion.getText());
        dts.setFecha(dato);
        dts.setTipoComprobante(dtsComprobante);
        dts.setImporte(Double.parseDouble(txtTotal.getText()));

        func.save(dts);
        cuentasCorriente();
        guardarDetalleVTA();
        if(txtIva.getText().length()!=0){guardaIva(); }
        
        inHabilitar();
        limpiaTabla();
    }

    public void guardarDetalleVTA() {

        GenericRepository<dDetalleVta, Long> funcVTA = new GenericRepository<dDetalleVta, Long>(factory) {
        };
        GenericRepository<dProductos, Long> funcPRO = new GenericRepository<dProductos, Long>(factory) {
        };
        

        GenericRepository<dStock, Long> funcSTO = new GenericRepository<dStock, Long>(factory) {
        };
        GenericRepository<dComisiones, Long> funcCOMI = new GenericRepository<dComisiones, Long>(factory) {
        };
        GenericRepository<dVendedor, Long> funcVENDED = new GenericRepository<dVendedor, Long>(factory) {
        };
        

       dVendedor dtsVendedor = funcVENDED.getById(Long.valueOf(txtIdVendedor.getText()));

        int fila = tableVenta.getRowCount();
        for (int x = 0; x < fila; x++) {

            String cod = String.valueOf(tableVenta.getValueAt(x, 0));
            String cant = String.valueOf(tableVenta.getValueAt(x, 2));
            String pre = String.valueOf(tableVenta.getValueAt(x, 3));

           
            dProductos dtsProductos = funcPRO.getById(Long.valueOf(cod));

            porcentajeComiManager funcM = new porcentajeComiManager(factory);
            Long pr = funcM.getProductosCategoria(Long.valueOf(cod));
            int categoria = Integer.parseInt(pr.toString());
            System.out.println(pr.toString());
            System.out.println(categoria);
            Double comi = funcM.getComisionProducto(Integer.parseInt(txtIdVendedor.getText()), categoria);

            System.out.println(comi);

            Double operacion = Double.valueOf(cant) * Double.valueOf(pre);
            Double result = (operacion / 100) * comi;

            dVentas dts1 = new dVentas();
            dDetalleVta dtsVent= new dDetalleVta();
            
            dtsVent.setCantidad(Integer.parseInt(cant));
            dtsVent.setPrecio(Double.parseDouble(pre));
            dtsVent.setProductos(dtsProductos);
            dtsVent.setVentas(dts);
            funcVTA.save(dtsVent);

            dStock stock = new dStock();
            stock.setFecha(dato);
            stock.setProducto(dtsProductos);
            stock.setCantidad(0);
            stock.setSalida(Integer.parseInt(cant));
            stock.setIdDetalleVta(dtsVent);
            funcSTO.save(stock);
            
            dComisiones dtsComi=new dComisiones();
            
            if(categoria !=3){
            dtsComi.setFecha(dato);
            dtsComi.setCantidad(Integer.parseInt(cant));
            dtsComi.setPrecio(Double.parseDouble(pre));
            dtsComi.setIdProducto(dtsProductos);
            dtsComi.setIdDetalleVta(dtsVent);
            dtsComi.setIdVendedor(dtsVendedor);
            dtsComi.setComision(result);
            funcCOMI.save(dtsComi);}
            else{System.out.println("es materia prima");}

        }
    }
      public void cuentasCorriente(){
        
          GenericRepository<dCuentasCorriente, Long> funcCC = new GenericRepository<dCuentasCorriente, Long>(factory) {
       };
           GenericRepository<dOperadores, Long> funcOP = new GenericRepository<dOperadores, Long>(factory) {
        }; 
      
        dOperadores dtsOpera = funcOP.getById(Long.valueOf(txtId.getText()));  
        dCuentasCorriente dtsCC =new dCuentasCorriente();
    
        dtsCC.setDebe(Double.valueOf(txtTotal.getText()));
        dtsCC.setHaber(0.0);
        dtsCC.setFecha(dato);
        dtsCC.setObservacion(txtTipoComprobante.getText()+" "+txtObservacion.getText());
        dtsCC.setOperadores(dtsOpera);
        dtsCC.setVentas(dts);
        if(txtNumero.getText().length()==0){
            dtsCC.setNumero(dts.getIdVentas().toString());
        }else{
            dtsCC.setNumero(txtNumero.getText());
        }
         dtsCC.setNumeroID(Integer.parseInt(dts.getIdVentas().toString()));
              
        funcCC.save(dtsCC);
        
        
    }

    public void obtenerFecha() {

        SimpleDateFormat formatoDelTexto = new SimpleDateFormat("dd-MM-yyyy");  ////// metodo para convertir string a date y colocarlo en jdatechooser   http://www.forosdelweb.com/f45/mysql-java-netbeans-java-sql-date-860869/
        String fecha = txtFecha.getText();

        try {

            dato = formatoDelTexto.parse(fecha);

        } catch (ParseException ex) {

            ex.printStackTrace();

        }

    }

    public void guardarDevolucion() {

        if (txtId.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "FALTA RAZON SOCIAL", "ADVERTENCIA", JOptionPane.ERROR_MESSAGE);
            txtId.requestFocus();
            return;
        }

        if (txtFecha.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "FALTA FECHA", "ADVERTENCIA", JOptionPane.ERROR_MESSAGE);
            txtFecha.requestFocus();
            return;
        }
        if (txtIdComprobante.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "FALTA COMPROBANTE", "ADVERTENCIA", JOptionPane.ERROR_MESSAGE);
            txtIdComprobante.requestFocus();
            return;
        }
        
        GenericRepository<dVentas, Long> func = new GenericRepository<dVentas, Long>(factory) {
        };
        
        GenericRepository<dOperadores, Long> funcOP = new GenericRepository<dOperadores, Long>(factory) {
        };  
        GenericRepository<dTipoComprobante, Long> funcCO = new GenericRepository<dTipoComprobante, Long>(factory) {
        };

        obtenerFecha();

        dOperadores dtsOpera = funcOP.getById(Long.valueOf(txtId.getText()));
        dTipoComprobante dtsComprobante = funcCO.getById(Long.valueOf(txtIdComprobante.getText()));

        dts.setOperadores(dtsOpera);
          if(txtNumero.getText().length()==0){
         dts.setComprobante(0);}
        else{
        dts.setComprobante(Integer.parseInt(txtNumero.getText()));}
        dts.setDescripcion(txtTipoComprobante.getText()+ " "+txtObservacion.getText());
        dts.setFecha(dato);
        dts.setTipoComprobante(dtsComprobante);
        dts.setImporte(Double.parseDouble(txtTotal.getText()));

        func.save(dts);
        cuentasCorrienteDevolucion();
        guardarDetalleVTAdevolucion();
        inHabilitar();
        limpiaTabla();
    }

    public void guardarDetalleVTAdevolucion() {

         GenericRepository<dDetalleVta, Long> funcVTA = new GenericRepository<dDetalleVta, Long>(factory) {
        };
        GenericRepository<dProductos, Long> funcPRO = new GenericRepository<dProductos, Long>(factory) {
        };
        

        GenericRepository<dStock, Long> funcSTO = new GenericRepository<dStock, Long>(factory) {
        };
        GenericRepository<dComisiones, Long> funcCOMI = new GenericRepository<dComisiones, Long>(factory) {
        };
        GenericRepository<dVendedor, Long> funcVENDED = new GenericRepository<dVendedor, Long>(factory) {
        };

        

        dVendedor dtsVendedor = funcVENDED.getById(Long.valueOf(txtIdVendedor.getText()));

        int fila = tableVenta.getRowCount();
        for (int x = 0; x < fila; x++) {

            String cod = String.valueOf(tableVenta.getValueAt(x, 0));
            String cant = String.valueOf(tableVenta.getValueAt(x, 2));
            String pre = String.valueOf(tableVenta.getValueAt(x, 3));

           
           dProductos dtsProductos = funcPRO.getById(Long.valueOf(cod));

            porcentajeComiManager funcM = new porcentajeComiManager(factory);
            Long pr = funcM.getProductosCategoria(Long.valueOf(cod));
            int categoria = Integer.parseInt(pr.toString());
            System.out.println(pr.toString());
            System.out.println(categoria);
            Double comi = funcM.getComisionProducto(Integer.parseInt(txtIdVendedor.getText()), categoria);

            System.out.println(comi);

            Double operacion = Double.valueOf(cant) * Double.valueOf(pre);
            Double result = (operacion / 100) * comi;

           dVentas dts1 = new dVentas();
            dDetalleVta dtsVent= new dDetalleVta();

            dtsVent.setCantidad(Integer.parseInt(cant));
            dtsVent.setPrecio(Double.parseDouble(pre));
            dtsVent.setProductos(dtsProductos);
            dtsVent.setVentas(dts);
            funcVTA.save(dtsVent);

            dStock stock = new dStock();
            stock.setFecha(dato);
            stock.setProducto(dtsProductos);
            stock.setCantidad(Integer.parseInt(cant));
            stock.setSalida(0);
            stock.setIdDetalleVta(dtsVent);
            funcSTO.save(stock);

            dComisiones dtsComi=new dComisiones();
            
            if(categoria !=3){
            dtsComi.setFecha(dato);
            dtsComi.setCantidad(Integer.parseInt(cant));
            dtsComi.setPrecio(Double.parseDouble(pre));
            dtsComi.setIdProducto(dtsProductos);
            dtsComi.setIdDetalleVta(dtsVent);
            dtsComi.setIdVendedor(dtsVendedor);
            dtsComi.setComision(-result);
            funcCOMI.save(dtsComi);}
            else{System.out.println("es materia prima");}
            
        }
    }
      public void cuentasCorrienteDevolucion(){
    
            GenericRepository<dCuentasCorriente, Long> funcCC = new GenericRepository<dCuentasCorriente, Long>(factory) {
       };
           GenericRepository<dOperadores, Long> funcOP = new GenericRepository<dOperadores, Long>(factory) {
        }; 
      
        dOperadores dtsOpera = funcOP.getById(Long.valueOf(txtId.getText()));  
        dCuentasCorriente dtsCC =new dCuentasCorriente();
        
    
        dtsCC.setDebe(0.0);
        dtsCC.setHaber(Double.valueOf(txtTotal.getText()));
        dtsCC.setFecha(dato);
        dtsCC.setObservacion(txtTipoComprobante.getText()+" "+txtObservacion.getText());
        dtsCC.setOperadores(dtsOpera);
        dtsCC.setVentas(dts);
        if(txtNumero.getText().length()==0){
            dtsCC.setNumero(dts.getIdVentas().toString());
        }else{
            dtsCC.setNumero(txtNumero.getText());
        }
         dtsCC.setNumeroID(Integer.parseInt(dts.getIdVentas().toString()));
        funcCC.save(dtsCC);
        
        
    }  
        public void guardaIva(){
    
     GenericRepository<dIva, Long> funcIva = new GenericRepository<dIva, Long>(factory) {
        };
        
           GenericRepository<dOperadores, Long> funcOP = new GenericRepository<dOperadores, Long>(factory) {
        }; 
            dIva dtsIva=new dIva();
      
        dOperadores dtsOpera = funcOP.getById(Long.valueOf(txtId.getText()));  
    
    dtsIva.setOperadores(dtsOpera);
    dtsIva.setFecha(dato);
    dtsIva.setVentas(dts);
    dtsIva.setIvaVta(Double.valueOf(txtIva.getText()));
    dtsIva.setIvaCpr(0.0);
    dtsIva.setOtros(0.0);
    funcIva.save(dtsIva);
    
    }

    
    public void fechaActual(){
   
   java.util.Date ahora = new java.util.Date();

     SimpleDateFormat sm = new SimpleDateFormat("dd-MM-yyyy");
      
             String strDate = sm.format(ahora);
             System.out.println(strDate);
             txtFecha.setText(strDate);
   }             

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtRazon = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtVendedor = new javax.swing.JTextField();
        txtIdVendedor = new javax.swing.JTextField();
        txtObservacion = new javax.swing.JTextField();
        txtTipoComprobante = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtLocalidad = new javax.swing.JTextField();
        txtIdComprobante = new javax.swing.JTextField();
        txtFecha = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        txtProducto = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtSubTotal = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVenta = new javax.swing.JTable();
        txtIva = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        radioIva = new javax.swing.JRadioButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setResizable(true);
        setTitle("VENTAS");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("FORMULARIO DE VENTAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Id Cliente");

        jLabel2.setText("Fecha");

        jLabel3.setText("Direccion");

        jLabel4.setText("Localidad");

        jLabel5.setText("Vendedor");

        jLabel6.setText("Tipo Comprobante");

        jLabel7.setText("Numero");

        jLabel8.setText("Observacion");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
        });

        txtRazon.setEditable(false);
        txtRazon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazonActionPerformed(evt);
            }
        });

        txtDireccion.setEditable(false);
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        txtVendedor.setEditable(false);
        txtVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVendedorActionPerformed(evt);
            }
        });

        txtIdVendedor.setEditable(false);
        txtIdVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdVendedorActionPerformed(evt);
            }
        });

        txtObservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObservacionActionPerformed(evt);
            }
        });

        txtTipoComprobante.setEditable(false);
        txtTipoComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoComprobanteActionPerformed(evt);
            }
        });

        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        txtLocalidad.setEditable(false);
        txtLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocalidadActionPerformed(evt);
            }
        });

        txtIdComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdComprobanteActionPerformed(evt);
            }
        });
        txtIdComprobante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdComprobanteKeyPressed(evt);
            }
        });

        try {
            txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDireccion)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRazon, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtObservacion)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtTipoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumero))
                                    .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txtTipoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Id");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Producto");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Cantidad");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Precio");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Total");

        txtIdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProductoActionPerformed(evt);
            }
        });
        txtIdProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdProductoKeyPressed(evt);
            }
        });

        txtProducto.setEditable(false);
        txtProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoActionPerformed(evt);
            }
        });

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProducto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSubTotal)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar)
                .addGap(10, 10, 10))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PRODUCTO", "CANTIDAD", "PRECIO", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(tableVenta);
        if (tableVenta.getColumnModel().getColumnCount() > 0) {
            tableVenta.getColumnModel().getColumn(0).setMaxWidth(50);
            tableVenta.getColumnModel().getColumn(2).setMaxWidth(100);
            tableVenta.getColumnModel().getColumn(3).setMaxWidth(100);
            tableVenta.getColumnModel().getColumn(4).setMaxWidth(200);
        }

        txtTotal.setEditable(false);

        jLabel14.setText("IVA");

        jLabel15.setText("TOTAL");

        btnGuardar.setText("CARGAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jButton3.setText("IMPRIMIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jLabel17.setText("SUB_TOTAL");

        txtSubtotal.setEditable(false);

        radioIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioIvaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioIva)))
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(94, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addGap(63, 63, 63)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(btnGuardar)
                            .addComponent(btnNuevo)))
                    .addComponent(radioIva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jButton3)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(82, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F9) {
            vTabla_Operador form = new vTabla_Operador();
            form.ventana = "ventas";
            form.toFront();
            form.setVisible(true);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_txtIdKeyPressed

    private void txtIdComprobanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdComprobanteKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F9) {
            vTabla_Comprob form = new vTabla_Comprob();
            form.ventana = "ventas";
            form.toFront();
            form.setVisible(true);
        }
    }//GEN-LAST:event_txtIdComprobanteKeyPressed

    private void txtIdProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdProductoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F9) {
            vTabla_Prod form = new vTabla_Prod();
            form.ventana = "ventas";
            form.toFront();
            form.setVisible(true);
        }
    }//GEN-LAST:event_txtIdProductoKeyPressed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        habilitar();

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregarProducto();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txtTipoComprobante.getText().equals("DEVOLUCION")) {
            guardarDevolucion();
        } else {
            guardar();
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tableVenta.getModel(); //TableProducto es el nombre de mi tabla ;) 
        dtm.removeRow(tableVenta.getSelectedRow());
        suma();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        operadoresManager funcOPP = new operadoresManager(factory);
        dOperadores op = funcOPP.getOperadorById(Long.valueOf(txtId.getText()));

        if(op!=null){
        txtRazon.setText(op.razonSocial);
        txtDireccion.setText(op.direccion);
        txtLocalidad.setText(op.localidad);
        txtIdVendedor.setText(op.vendedores.idVendedor.toString());
        txtVendedor.setText(op.vendedores.nombre);
        txtId.transferFocus();
        }else{
        JOptionPane.showMessageDialog(null,"no exite operador");
        return;
        }
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtRazonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazonActionPerformed
        txtRazon.transferFocus();
    }//GEN-LAST:event_txtRazonActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        txtDireccion.transferFocus();
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalidadActionPerformed
        txtLocalidad.transferFocus();
    }//GEN-LAST:event_txtLocalidadActionPerformed

    private void txtIdVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdVendedorActionPerformed
        txtIdVendedor.transferFocus();
    }//GEN-LAST:event_txtIdVendedorActionPerformed

    private void txtVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVendedorActionPerformed
        txtVendedor.transferFocus();
    }//GEN-LAST:event_txtVendedorActionPerformed

    private void txtIdComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdComprobanteActionPerformed
        comprobanteManager funcCOMPROBAN = new comprobanteManager(factory);
        dTipoComprobante tipo = funcCOMPROBAN.getComprobanteById(Long.valueOf(txtIdComprobante.getText()));
        
        if(tipo!=null){
        txtTipoComprobante.setText(tipo.getComprobante());

        txtIdComprobante.transferFocus();
        }else{
        JOptionPane.showMessageDialog(null,"no exite comprobante");
        return;
        }
    }//GEN-LAST:event_txtIdComprobanteActionPerformed

    private void txtTipoComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoComprobanteActionPerformed
        txtTipoComprobante.transferFocus();
    }//GEN-LAST:event_txtTipoComprobanteActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        txtNumero.transferFocus();
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtObservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObservacionActionPerformed
        txtObservacion.transferFocus();
    }//GEN-LAST:event_txtObservacionActionPerformed

    private void txtIdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProductoActionPerformed
          if (txtIdProducto.getText().length() != 0) {
             GenericRepository<dProductos, Long> funcPRO = new GenericRepository<dProductos, Long>(factory) {
      };
            
            dProductos pr = funcPRO.getById(Long.valueOf(txtIdProducto.getText()));
            
            if(pr!=null){
            txtProducto.setText(pr.productos);
            txtIdProducto.transferFocus();
            }else{
            JOptionPane.showMessageDialog(null,"no exite producto");
            return;
            }
        } else {

            return;
        }
    }//GEN-LAST:event_txtIdProductoActionPerformed

    private void txtProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoActionPerformed
        txtProducto.transferFocus();
    }//GEN-LAST:event_txtProductoActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        txtCantidad.transferFocus();
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        txtPrecio.transferFocus();
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//       dVentas dtsE =new dVentas();
//       dtsE=func.getById(1L);
//        func.delete(dtsE);
        porcentajeComiManager funcM = new porcentajeComiManager(factory);
        Double comi = funcM.getComisionProducto(1, 1);
        System.out.println(comi);

        dProductos prr = new dProductos();
        //prr=funcM.getProductosComision(1L);
        Long pr = funcM.getProductosCategoria(1L);
        //System.out.println(prr.getCategoria().getIdCategoriaPR().toString());
        System.out.println(pr);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void radioIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioIvaActionPerformed
        if(radioIva.isSelected()){
            Double sub= Double.valueOf(txtSubtotal.getText());
            Double iva= sub*21/100;

            txtIva.setText(String.valueOf(iva));
            Double t=sub+iva;

            txtTotal.setText(String.valueOf(t));
        }else{
            txtIva.setText("");
            txtTotal.setText(txtSubtotal.getText());}
    }//GEN-LAST:event_radioIvaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioIva;
    private javax.swing.JTable tableVenta;
    private javax.swing.JTextField txtCantidad;
    protected static javax.swing.JTextField txtDireccion;
    private javax.swing.JFormattedTextField txtFecha;
    protected static javax.swing.JTextField txtId;
    protected static javax.swing.JTextField txtIdComprobante;
    protected static javax.swing.JTextField txtIdProducto;
    protected static javax.swing.JTextField txtIdVendedor;
    private javax.swing.JTextField txtIva;
    protected static javax.swing.JTextField txtLocalidad;
    private javax.swing.JTextField txtNumero;
    protected static javax.swing.JTextField txtObservacion;
    private javax.swing.JTextField txtPrecio;
    protected static javax.swing.JTextField txtProducto;
    protected static javax.swing.JTextField txtRazon;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtSubtotal;
    protected static javax.swing.JTextField txtTipoComprobante;
    private javax.swing.JTextField txtTotal;
    protected static javax.swing.JTextField txtVendedor;
    // End of variables declaration//GEN-END:variables
}
